[build]
command = "npm run build"
publish = "out"

# [[redirects]]
#     from = "/static/images/kids.jpg"
#     to = "/static/images/kids.jpg"
#     status = 200

# [[redirects]]
#     from = "/*"
#     to = "/my404.html"
#     status = 404
