[build]
command = "npm run build"
publish = ".next"

[[redirects]]
    from = "/images/kids.jpg"
    to = "/images/kids.jpg"
    status = 200

[[redirects]]
    from = "/*"
    to = "/"
    status = 200
