[build]
command = "npm run build"
publish = ".next"

# [[redirects]]
#     from = "/static/images/kids.jpg"
#     to = "/static/images/kids.jpg"
#     status = 200

[[redirects]]
    from = "/*"
    to = "/404.html"
    status = 404
